import type { Venue } from "./types";

export const VENUES: Venue[] = [
  {
    id: "heteroclito",
    no: 14,
    name: "Heteroclito",
    tagline: "Natural wine cave hidden under Monastiraki. Zero pretension.",
    note: "On rainy Tuesdays the back room is the whole point.",
    neighborhood: "Monastiraki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "19:00 – 02:00",
    walkMin: 5,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9758,
    lng: 23.7235,
    tags: ["Natural Wine", "Cave Vibes", "No Tourists"],
  },
  {
    id: "baba-au-rum",
    no: 11,
    name: "Baba Au Rum",
    tagline: "Top-50 cocktail bar in the world. Doesn't act like it.",
    note: "Order the Tipsy Palmer. Trust.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["First Date", "Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "19:00 – 03:00",
    walkMin: 7,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9762,
    lng: 23.7229,
    sponsored: true,
    tags: ["Award-Winning", "Cocktail Nerds", "Date Classic"],
  },
  {
    id: "noel",
    no: 22,
    name: "Noël",
    tagline: "Looks like the lounge of a hotel that never opened. Tastes like the bar of one that should.",
    note: "Tell them BAM sent you. They will pretend not to know what you mean.",
    neighborhood: "Psiri",
    vibe: "Cocktail Bar",
    budget: "€€€",
    occasions: ["Friday Night", "First Date"],
    image: "https://images.unsplash.com/photo-1543007631-283050bb3e8c?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "19:30 – 03:00",
    walkMin: 8,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9769,
    lng: 23.7201,
    tags: ["All-Day", "Moody", "Neighbourhood Gem"],
  },
  {
    id: "stavlos",
    no: 26,
    name: "Stavlos",
    tagline: "Rooftop without the Acropolis tax. You can hear each other.",
    note: "Bar level only — skip the restaurant floor.",
    neighborhood: "Thissio",
    vibe: "Rooftop",
    budget: "€€",
    occasions: ["Anniversary", "First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "17:00 – 02:00",
    walkMin: 12,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9735,
    lng: 23.7199,
    sponsored: true,
    tags: ["Acropolis View", "Historic", "Outdoor"],
  },
  {
    id: "half-note",
    no: 33,
    name: "Half Note Jazz Club",
    tagline: "The best live jazz in Athens. Reserve the booth by the stage.",
    note: "Check their calendar first — shows sell out two weeks ahead.",
    neighborhood: "Pangrati",
    vibe: "Jazz Club",
    budget: "€€€",
    occasions: ["Anniversary", "Something Different"],
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=700&h=500&fit=crop&auto=format",
    openNow: false,
    hours: "21:00 – 02:00",
    walkMin: 18,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9701,
    lng: 23.7412,
    tags: ["Live Music", "Intimate", "Athens Legend"],
  },
  {
    id: "wine-not",
    no: 8,
    name: "Wine Not",
    tagline: "60 Greek labels by the glass. The sommelier actually knows you.",
    note: "Ask for the skin-contact orange. They always have one open.",
    neighborhood: "Koukaki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Anniversary"],
    image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "18:00 – 01:00",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9681,
    lng: 23.7265,
    tags: ["Greek Wines", "Intimate", "No Tourists"],
  },
  {
    id: "psaras",
    no: 3,
    name: "Psaras",
    tagline: "Open since 1898. Same menu, same waiters, same lamb. Time travel.",
    note: "Cash works. Card sometimes.",
    neighborhood: "Monastiraki",
    vibe: "Dinner",
    budget: "€€",
    occasions: ["Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "12:00 – 00:00",
    walkMin: 10,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9756,
    lng: 23.7248,
    tags: ["Legendary", "Greek Kitchen", "Outdoor"],
  },
  {
    id: "funky-gourmet",
    no: 47,
    name: "Funky Gourmet",
    tagline: "Two Michelin stars. For the date you want them to remember too.",
    note: "Book 3 weeks ahead minimum. Tasting menu only — commit.",
    neighborhood: "Psiri",
    vibe: "Dinner",
    budget: "€€€",
    occasions: ["Anniversary"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=700&h=500&fit=crop&auto=format",
    openNow: false,
    hours: "20:00 – 00:00",
    walkMin: 20,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9775,
    lng: 23.7169,
    tags: ["Michelin", "Tasting Menu", "Special Occasion"],
  },
  {
    id: "roof-garden",
    no: 19,
    name: "Roof Garden at King George",
    tagline: "Rooftop dining above Syntagma. The city lit up below you.",
    note: "Window table for two — request it when booking. Worth the ask.",
    neighborhood: "Kolonaki",
    vibe: "Rooftop",
    budget: "€€€",
    occasions: ["Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1563327055-6e6c30d4f2eb?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "18:00 – 00:00",
    walkMin: 3,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9755,
    lng: 23.7338,
    sponsored: true,
    tags: ["City Views", "Luxury", "5-Star Hotel"],
  },
  {
    id: "cluedo-escape",
    no: 42,
    name: "Cluedo Athens",
    tagline: "English-language escape room. If the date dies, the puzzle gets blamed.",
    note: "Book 24h ahead. Wear closed-toe shoes.",
    neighborhood: "Exarcheia",
    vibe: "Activity",
    budget: "€",
    occasions: ["Something Different", "First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "10:00 – 22:00",
    walkMin: 14,
    bookingUrl: "https://getyourguide.com",
    bookingPartner: "GetYourGuide",
    lat: 37.9838,
    lng: 23.7330,
    tags: ["Team Game", "1 Hour", "No Tourists"],
  },
  {
    id: "politia",
    no: 16,
    name: "Politia",
    tagline: "Neighbourhood bar in Kypseli. Zero tourist traffic, zero pretension.",
    note: "Get there before 21:00 for a seat at the bar.",
    neighborhood: "Kypseli",
    vibe: "Cocktail Bar",
    budget: "€",
    occasions: ["Friday Night", "First Date"],
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "18:00 – 02:00",
    walkMin: 5,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9901,
    lng: 23.7367,
    tags: ["Local Crowd", "Cheap Drinks", "Hidden"],
  },
  {
    id: "seven-jokers",
    no: 37,
    name: "Seven Jokers",
    tagline: "Comedy and improv club. Bring a date, laugh together, be surprised.",
    note: "Sundays in English. Greek on Fridays.",
    neighborhood: "Kolonaki",
    vibe: "Comedy",
    budget: "€€",
    occasions: ["Something Different", "Friday Night"],
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "21:00 show",
    walkMin: 9,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9794,
    lng: 23.7403,
    tags: ["Live Comedy", "Intimate Venue", "Unique Night"],
  },
  {
    id: "oinoscent",
    no: 29,
    name: "Oinoscent",
    tagline: "Wine bar + shop in Koukaki. Buy a bottle, drink it at the bar.",
    note: "Natural wine section in the back. The staff picks well.",
    neighborhood: "Koukaki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "17:00 – 01:00",
    walkMin: 8,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9677,
    lng: 23.7281,
    tags: ["Retail + Bar", "Relaxed", "Greek Labels"],
  },
  {
    id: "tailor-made",
    no: 5,
    name: "Tailor Made",
    tagline: "Craft cocktail bar in Monastiraki that actually makes you feel cool.",
    note: "Bar seats by the window. The booth is for tourists.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["Friday Night", "Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "08:00 – 02:00",
    walkMin: 4,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9771,
    lng: 23.7224,
    tags: ["Craft Cocktails", "Moody Lighting", "Date Classic"],
  },
  {
    id: "athinais",
    no: 51,
    name: "Athinais",
    tagline: "Industrial cultural space. Catch a screening or just drink in the courtyard.",
    note: "Check what's on before you go — the courtyard is the real draw.",
    neighborhood: "Petralona",
    vibe: "Experience",
    budget: "€€",
    occasions: ["Something Different", "Anniversary"],
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=700&h=500&fit=crop&auto=format",
    openNow: false,
    hours: "18:00 – 01:00",
    walkMin: 15,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9712,
    lng: 23.7165,
    tags: ["Arts Space", "Cinema", "Courtyard"],
  },
  {
    id: "couleur-locale",
    name: "Couleur Locale",
    no: 31,
    tagline: "Hidden rooftop above Monastiraki. Raw Acropolis view without the crowd.",
    note: "Third-floor rooftop — don't stop at the café below.",
    neighborhood: "Monastiraki",
    vibe: "Rooftop",
    budget: "€€",
    occasions: ["First Date", "Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "09:00 – 02:00",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9764,
    lng: 23.7235,
    sponsored: true,
    tags: ["Secret Rooftop", "Acropolis View", "Instagrammable"],
  },
  {
    id: "manesis",
    no: 23,
    name: "Manesis",
    tagline: "Tiny wine bar in Pangrati run by one guy who loves what he does.",
    note: "No reservations. Get there at 20:00.",
    neighborhood: "Pangrati",
    vibe: "Wine Bar",
    budget: "€",
    occasions: ["Friday Night", "Something Different"],
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "19:00 – 01:00",
    walkMin: 10,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "Direct",
    lat: 37.9692,
    lng: 23.7408,
    tags: ["One-Person Show", "Cheap Wine", "Local Secret"],
  },
  {
    id: "akrotiri",
    no: 44,
    name: "Akrotiri Lounge",
    tagline: "Glyfada beach bar. Sunset drinks with your feet in the sand.",
    note: "Summer only. Takes a commitment to get there — worth it.",
    neighborhood: "Glyfada",
    vibe: "Experience",
    budget: "€€€",
    occasions: ["Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "11:00 – 02:00",
    walkMin: 45,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.8673,
    lng: 23.7549,
    tags: ["Beach", "Sunset", "Summer Only"],
  },
  {
    id: "shooting-club",
    no: 55,
    name: "Athens Shooting Club",
    tagline: "Holding a bow makes everyone hotter. We don't make the rules.",
    note: "Book 24h ahead. Wear closed-toe shoes.",
    neighborhood: "Exarcheia",
    vibe: "Activity",
    budget: "€€",
    occasions: ["Something Different", "First Date"],
    image: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=700&h=500&fit=crop&auto=format",
    openNow: false,
    hours: "10:00 – 22:00",
    walkMin: 22,
    bookingUrl: "https://getyourguide.com",
    bookingPartner: "GetYourGuide",
    lat: 37.9858,
    lng: 23.7395,
    tags: ["Unexpected", "Beginner-Friendly", "Adrenaline"],
  },
  {
    id: "six-d-o-g-s",
    no: 7,
    name: "Six D.O.G.S",
    tagline: "Half garden, half cocktail bar, half music venue. Yes that's three halves.",
    note: "Show up before 21:00 or you wait in line.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["Friday Night", "Something Different"],
    image: "https://images.unsplash.com/photo-1574096079513-d8259312b785?w=700&h=500&fit=crop&auto=format",
    openNow: true,
    hours: "18:00 – 03:00",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9773,
    lng: 23.7233,
    tags: ["Multi-Level", "Garden", "Cultural Events"],
  },
];

export const NEIGHBORHOODS = [
  "Koukaki",
  "Pangrati",
  "Exarcheia",
  "Kolonaki",
  "Petralona",
  "Kypseli",
  "Monastiraki",
  "Psiri",
  "Thissio",
  "Glyfada",
] as const;

export const NEIGHBORHOOD_GR: Record<string, string> = {
  Koukaki:    "Κουκάκι",
  Pangrati:   "Παγκράτι",
  Exarcheia:  "Εξάρχεια",
  Kolonaki:   "Κολωνάκι",
  Petralona:  "Πετράλωνα",
  Kypseli:    "Κυψέλη",
  Monastiraki:"Μοναστηράκι",
  Psiri:      "Ψυρρή",
  Thissio:    "Θησείο",
  Glyfada:    "Γλυφάδα",
};

export const VIBES = [
  "Wine Bar",
  "Cocktail Bar",
  "Dinner",
  "Rooftop",
  "Jazz Club",
  "Activity",
  "Comedy",
  "Experience",
] as const;

export const BUDGETS = ["€", "€€", "€€€"] as const;

export const OCCASIONS = [
  "First Date",
  "Anniversary",
  "Friday Night",
  "Something Different",
] as const;

// Occasion metadata with Greek labels and the editorial "spice" line
export const OCCASIONS_DATA = [
  { id: "First Date",         gr: "Πρώτο ραντεβού", spice: "Bar seating, plausible escape route, cocktail menu." },
  { id: "Anniversary",        gr: "Επέτειος",        spice: "Worth the cab fare. Order the second bottle." },
  { id: "Friday Night",       gr: "Παρασκευή",       spice: "Most likely to make Saturday confusing." },
  { id: "Something Different",gr: "Κάτι αλλιώς",    spice: "Skip dinner. Try the comedy night or the shooting range." },
] as const;
