import type { Venue } from "./types";

export const VENUES: Venue[] = [
  {
    id: "heteroclito",
    name: "Heteroclito",
    tagline: "Natural wine cave hidden under Monastiraki. Zero pretension.",
    neighborhood: "Monastiraki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=700&h=500&fit=crop&auto=format",
    walkMin: 5,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9758,
    lng: 23.7235,
    tags: ["Natural Wine", "Cave Vibes", "No Tourists"],
  },
  {
    id: "baba-au-rum",
    name: "Baba Au Rum",
    tagline: "Athens' finest cocktail bar. Get the rum old-fashioned.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["First Date", "Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=700&h=500&fit=crop&auto=format",
    walkMin: 7,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9762,
    lng: 23.7229,
    sponsored: true,
    tags: ["Award-Winning", "Cocktail Nerds", "Date Classic"],
  },
  {
    id: "noel",
    name: "Noël",
    tagline: "All-day bar in Psiri that turns into a date playground after 10.",
    neighborhood: "Psiri",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["Friday Night", "First Date"],
    image: "https://images.unsplash.com/photo-1543007631-283050bb3e8c?w=700&h=500&fit=crop&auto=format",
    walkMin: 8,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9769,
    lng: 23.7201,
    tags: ["All-Day", "Moody", "Neighbourhood Gem"],
  },
  {
    id: "stavlos",
    name: "Stavlos",
    tagline: "Old royal stables turned rooftop bar. The Acropolis view is free.",
    neighborhood: "Thissio",
    vibe: "Rooftop",
    budget: "€€",
    occasions: ["Anniversary", "First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=700&h=500&fit=crop&auto=format",
    walkMin: 12,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9735,
    lng: 23.7199,
    sponsored: true,
    tags: ["Acropolis View", "Historic", "Outdoor"],
  },
  {
    id: "half-note",
    name: "Half Note Jazz Club",
    tagline: "The best live jazz in Athens. Reserve the booth by the stage.",
    neighborhood: "Pangrati",
    vibe: "Jazz Club",
    budget: "€€€",
    occasions: ["Anniversary", "Something Different"],
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=700&h=500&fit=crop&auto=format",
    walkMin: 18,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9701,
    lng: 23.7412,
    tags: ["Live Music", "Intimate", "Athens Legend"],
  },
  {
    id: "wine-not",
    name: "Wine Not",
    tagline: "60 Greek labels by the glass. The sommelier actually knows you.",
    neighborhood: "Koukaki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Anniversary"],
    image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=700&h=500&fit=crop&auto=format",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9681,
    lng: 23.7265,
    tags: ["Greek Wines", "Intimate", "No Tourists"],
  },
  {
    id: "psaras",
    name: "Psaras",
    tagline: "Established 1898. Taverna in Plaka that has never disappointed.",
    neighborhood: "Monastiraki",
    vibe: "Dinner",
    budget: "€€",
    occasions: ["Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&h=500&fit=crop&auto=format",
    walkMin: 10,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9756,
    lng: 23.7248,
    tags: ["Legendary", "Greek Kitchen", "Outdoor"],
  },
  {
    id: "funky-gourmet",
    name: "Funky Gourmet",
    tagline: "Two Michelin stars in Keramikos. For the date you want to remember.",
    neighborhood: "Psiri",
    vibe: "Dinner",
    budget: "€€€",
    occasions: ["Anniversary"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=700&h=500&fit=crop&auto=format",
    walkMin: 20,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9775,
    lng: 23.7169,
    tags: ["Michelin", "Tasting Menu", "Special Occasion"],
  },
  {
    id: "roof-garden",
    name: "Roof Garden — King George",
    tagline: "Rooftop dining above Syntagma. The city lit up below you.",
    neighborhood: "Kolonaki",
    vibe: "Rooftop",
    budget: "€€€",
    occasions: ["Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1563327055-6e6c30d4f2eb?w=700&h=500&fit=crop&auto=format",
    walkMin: 3,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9755,
    lng: 23.7338,
    sponsored: true,
    tags: ["City Views", "Luxury", "5-Star Hotel"],
  },
  {
    id: "cluedo-escape",
    name: "Cluedo Athens",
    tagline: "The escape room Athens couples actually rate. 60 minutes, no phones.",
    neighborhood: "Exarcheia",
    vibe: "Activity",
    budget: "€",
    occasions: ["Something Different", "First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=700&h=500&fit=crop&auto=format",
    walkMin: 14,
    bookingUrl: "https://getyourguide.com",
    bookingPartner: "GetYourGuide",
    lat: 37.9838,
    lng: 23.7330,
    tags: ["Team Game", "1 Hour", "No Tourists"],
  },
  {
    id: "politia",
    name: "Politia",
    tagline: "Neighbourhood bar in Kypseli with zero tourist traffic.",
    neighborhood: "Kypseli",
    vibe: "Cocktail Bar",
    budget: "€",
    occasions: ["Friday Night", "First Date"],
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=700&h=500&fit=crop&auto=format",
    walkMin: 5,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9901,
    lng: 23.7367,
    tags: ["Local Crowd", "Cheap Drinks", "Hidden"],
  },
  {
    id: "seven-jokers",
    name: "Seven Jokers",
    tagline: "Comedy and improv club. Bring a date, laugh together, be surprised.",
    neighborhood: "Kolonaki",
    vibe: "Comedy",
    budget: "€€",
    occasions: ["Something Different", "Friday Night"],
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=700&h=500&fit=crop&auto=format",
    walkMin: 9,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9794,
    lng: 23.7403,
    tags: ["Live Comedy", "Intimate Venue", "Unique Night"],
  },
  {
    id: "oinoscent",
    name: "Oinoscent",
    tagline: "Wine bar + shop in Koukaki. Buy a bottle, drink it at the bar.",
    neighborhood: "Koukaki",
    vibe: "Wine Bar",
    budget: "€€",
    occasions: ["First Date", "Friday Night"],
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=700&h=500&fit=crop&auto=format",
    walkMin: 8,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9677,
    lng: 23.7281,
    tags: ["Retail + Bar", "Relaxed", "Greek Labels"],
  },
  {
    id: "tailor-made",
    name: "Tailor Made",
    tagline: "Craft cocktail bar in Monastiraki that actually makes you feel cool.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["Friday Night", "Anniversary", "First Date"],
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=700&h=500&fit=crop&auto=format",
    walkMin: 4,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9771,
    lng: 23.7224,
    tags: ["Craft Cocktails", "Moody Lighting", "Date Classic"],
  },
  {
    id: "athinais",
    name: "Athinais",
    tagline: "Industrial cultural space — catch a screening or just drink in the courtyard.",
    neighborhood: "Petralona",
    vibe: "Experience",
    budget: "€€",
    occasions: ["Something Different", "Anniversary"],
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=700&h=500&fit=crop&auto=format",
    walkMin: 15,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9712,
    lng: 23.7165,
    tags: ["Arts Space", "Cinema", "Courtyard"],
  },
  {
    id: "couleur-locale",
    name: "Couleur Locale",
    tagline: "Hidden rooftop above Monastiraki with a raw Acropolis view. Secret spot.",
    neighborhood: "Monastiraki",
    vibe: "Rooftop",
    budget: "€€",
    occasions: ["First Date", "Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=700&h=500&fit=crop&auto=format",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9764,
    lng: 23.7235,
    sponsored: true,
    tags: ["Secret Rooftop", "Acropolis View", "Instagrammable"],
  },
  {
    id: "manesis",
    name: "Manesis",
    tagline: "Tiny wine bar in Pangrati run by one guy who loves what he does.",
    neighborhood: "Pangrati",
    vibe: "Wine Bar",
    budget: "€",
    occasions: ["Friday Night", "Something Different"],
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=700&h=500&fit=crop&auto=format",
    walkMin: 10,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "Direct",
    lat: 37.9692,
    lng: 23.7408,
    tags: ["One-Person Show", "Cheap Wine", "Local Secret"],
  },
  {
    id: "akrotiri",
    name: "Akrotiri Lounge",
    tagline: "Glyfada beach bar. Sunset drinks with your feet in the sand.",
    neighborhood: "Glyfada",
    vibe: "Experience",
    budget: "€€€",
    occasions: ["Anniversary", "Friday Night"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&h=500&fit=crop&auto=format",
    walkMin: 45,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.8673,
    lng: 23.7549,
    tags: ["Beach", "Sunset", "Summer Only"],
  },
  {
    id: "shooting-club",
    name: "Athens Shooting Club",
    tagline: "Certified shooting range for beginners. A date she won't see coming.",
    neighborhood: "Exarcheia",
    vibe: "Activity",
    budget: "€€",
    occasions: ["Something Different", "First Date"],
    image: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=700&h=500&fit=crop&auto=format",
    walkMin: 22,
    bookingUrl: "https://getyourguide.com",
    bookingPartner: "GetYourGuide",
    lat: 37.9858,
    lng: 23.7395,
    tags: ["Unexpected", "Beginner-Friendly", "Adrenaline"],
  },
  {
    id: "six-d-o-g-s",
    name: "Six D.O.G.S",
    tagline: "Bar + garden + rooftop in Monastiraki. Three dates in one venue.",
    neighborhood: "Monastiraki",
    vibe: "Cocktail Bar",
    budget: "€€",
    occasions: ["Friday Night", "Something Different"],
    image: "https://images.unsplash.com/photo-1574096079513-d8259312b785?w=700&h=500&fit=crop&auto=format",
    walkMin: 6,
    bookingUrl: "https://e-table.gr",
    bookingPartner: "e-table",
    lat: 37.9773,
    lng: 23.7233,
    tags: ["Multi-Level", "Garden", "Cultural Events"],
  },
];

export const NEIGHBORHOODS = [
  "Koukaki",
  "Pangrati",
  "Exarcheia",
  "Kolonaki",
  "Petralona",
  "Kypseli",
  "Monastiraki",
  "Psiri",
  "Thissio",
  "Glyfada",
] as const;

export const VIBES = [
  "Wine Bar",
  "Cocktail Bar",
  "Dinner",
  "Rooftop",
  "Jazz Club",
  "Activity",
  "Comedy",
  "Experience",
] as const;

export const BUDGETS = ["€", "€€", "€€€"] as const;

export const OCCASIONS = [
  "First Date",
  "Anniversary",
  "Friday Night",
  "Something Different",
] as const;
